backend:
  name: git-gateway
  repo: efdevcon/devcon-website
  branch: '$BRANCH'
  accept_roles:
    - admin
    - editor

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'


publish_mode: editorial_workflow
media_folder: static/assets/uploads/images
public_folder: /assets/uploads/images

i18n:
  structure: multiple_folders
  locales: [en, es]
  default_locale: en

collections:
  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    folder: 'src/content/pages'
    slug: '{{slug}}'
    create: true
    i18n: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string', i18n: true }
      - { name: 'description', label: 'Description', widget: 'text', i18n: true, required: false }
      - { name: 'body', label: 'Body', widget: 'markdown', i18n: true }
      - {
          name: 'tags',
          label: 'Tags',
          widget: 'relation',
          i18n: 'duplicate',
          required: false,
          collection: 'tags',
          value_field: '{{slug}}',
          search_fields: ['title'],
          multiple: true,
        }
      - {
          name: 'template',
          label: 'Template',
          widget: 'select',
          i18n: 'duplicate',
          options: ['none', 'blogs', 'city-guide', 'content', 'dips', 'faq', news', 'road-to-devcon'],
          default: 'content',
        }
      - {
          name: 'translationVerified',
          label: 'If this translation has been (manually) verified',
          widget: 'boolean',
          i18n: 'duplicate',
          required: false,
          default: false,
        }

  - name: 'notification'
    label: 'Notifications'
    label_singular: 'Notification'
    folder: 'src/content/notifications'
    i18n: true
    fields:
      - {
          name: 'body',
          label: 'Body',
          pattern: ['^.{0,50}$', 'Must have less than 50 characters'],
          widget: 'markdown',
          i18n: true,
        }
      - { name: 'url', label: 'URL', widget: 'string', i18n: 'duplicate', required: false }
      - { name: 'label', Label: 'Label', widget: 'string', i18n: true, required: false }
      - {
          name: 'labelType',
          Label: 'Label Type',
          widget: 'select',
          options: ['neutral', 'success', 'error'],
          required: false,
          i18n: 'duplicate',
        }
      - { label: 'Active', name: 'active', widget: 'boolean', default: true, i18n: duplicate }

  - name: 'news'
    label: 'News'
    label_singular: 'News item'
    folder: 'src/content/news'
    create: true
    i18n: true
    fields:
      - { name: 'url', label: 'URL', widget: 'string', i18n: 'duplicate', required: false }
      - { name: 'title', label: 'Title', widget: 'string', i18n: true, required: true }
      - {
          name: 'body',
          label: 'Body',
          pattern: ['^.{0,280}$', 'Must have less than 280 characters'],
          widget: 'markdown',
          i18n: true,
        }
      - {
          name: 'tags',
          label: 'Tags',
          widget: 'relation',
          i18n: 'duplicate',
          required: false,
          collection: 'tags',
          value_field: '{{slug}}',
          search_fields: ['title'],
          multiple: true,
        }
      - { name: 'author', label: 'Author', widget: 'string', required: false }
      - { name: 'date', label: 'Date', widget: datetime, picker_utc: true, i18n: 'duplicate', required: true }

  - name: 'news-tweets'
    label: 'News: Tweets'
    label_singular: 'News item: Tweet'
    folder: 'src/content/news-external/tweets'
    create: true
    fields:
      - { name: 'url', label: 'URL', widget: 'string' }
      - { name: 'title', label: 'Title', hidden: true, required: true }
      - {
          name: 'body',
          label: 'Body',
          pattern: ['^.{0,280}$', 'Must have less than 280 characters'],
          widget: 'markdown',
        }
      - {
          name: 'tags',
          label: 'Tags',
          widget: 'relation',
          required: false,
          collection: 'tags',
          value_field: '{{slug}}',
          search_fields: ['title'],
          multiple: true,
        }
      - { name: 'date', label: 'Date', widget: datetime, hidden: true, picker_utc: true, required: true }

  - name: 'news-blog-posts'
    label: 'News: Blog Posts'
    label_singular: 'News item: Blog Post'
    folder: 'src/content/news-external/blog-posts'
    create: true
    fields:
      - { name: 'url', label: 'URL', widget: 'string' }
      - { name: 'title', label: 'Title' }
      - {
          name: 'body',
          label: 'Body',
          pattern: ['^.{0,280}$', 'Must have less than 280 characters'],
          widget: 'markdown',
        }
      - {
          name: 'tags',
          label: 'Tags',
          widget: 'relation',
          required: false,
          collection: 'tags',
          value_field: '{{slug}}',
          search_fields: ['title'],
          multiple: true,
        }
      - { name: 'date', label: 'Date', widget: datetime, hidden: true, picker_utc: true, required: true }

  - name: 'Content sections'
    label: 'Content sections'
    label_singular: 'Content section'
    folder: 'src/content/sections'
    create: true
    i18n: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string', i18n: true }
      - {
          name: 'showTitle',
          label: 'Show title',
          widget: 'boolean',
          i18n: 'duplicate',
          required: false,
          default: false,
        }
      - { name: 'left', widget: 'markdown', i18n: true }
      - { name: 'right', widget: 'markdown', i18n: true }

  - name: faq
    label: FAQ
    label_singular: FAQ
    folder: src/content/faq
    create: true
    i18n: true
    fields:
      - { name: title, label: Title, widget: string, i18n: true }
      - { name: body, label: Body, widget: markdown, i18n: true }
      - {
          name: category,
          label: Category,
          widget: relation,
          i18n: duplicate,
          collection: categories,
          value_field: '{{slug}}',
          search_fields: ['title'],
          multiple: false,
        }
      - {
          name: order,
          label: Order,
          widget: number,
          i18n: duplicate,
          required: false,
          value_type: int,
          min: 1,
          max: 1000,
          step: 1,
        }

  - name: categories
    label: Categories
    label_singular: Category
    folder: src/content/categories
    create: true
    i18n: true
    fields:
      - { name: title, label: Title, widget: string, i18n: true }

  - name: tags
    label: Tags
    label_singular: Tag
    folder: src/content/tags
    create: true
    i18n: true
    fields:
      - { name: title, label: Title, widget: string, i18n: true }

  - name: headers
    label: Headers
    label_singular: Header
    folder: src/content/headers
    create: true
    i18n: true
    fields:
      - { name: title, label: Title, widget: string, i18n: true }

  - name: links
    label: Links
    label_singular: Link
    folder: src/content/links
    create: true
    i18n: true
    fields:
      - { name: title, label: Title, widget: string, i18n: true }
      - { name: url, label: URL, widget: string, i18n: duplicate }

  - name: navigation
    label: Navigation
    label_singular: Navigation
    folder: src/content/navigation
    create: true
    i18n: false
    fields:
      - { name: title, label: Title, widget: string }
      - label: Links
        name: links
        widget: list
        collapsed: false
        types:
          - label: Page
            name: page
            fields:
              - {
                  name: slug,
                  label: Page,
                  value_field: '{{slug}}',
                  search_fields: ['{{slug}}'],
                  widget: relation,
                  collection: pages,
                }
          - label: Link
            name: link
            fields:
              - {
                  name: slug,
                  label: Link,
                  value_field: '{{slug}}',
                  search_fields: ['{{slug}}'],
                  widget: relation,
                  collection: links,
                }
          - label: Header
            name: header
            fields:
              - {
                  name: slug,
                  label: Header,
                  value_field: '{{slug}}',
                  search_fields: ['{{slug}}'],
                  widget: relation,
                  collection: headers,
                }
          - label: Links
            name: links
            fields:
              - {
                  name: slug,
                  label: Header,
                  value_field: '{{slug}}',
                  search_fields: ['{{slug}}'],
                  widget: relation,
                  collection: headers,
                }
              - label: Links
                name: links
                widget: list
                types:
                  - label: Page
                    name: page
                    fields:
                      - {
                          name: slug,
                          label: Page,
                          value_field: '{{slug}}',
                          search_fields: ['{{slug}}'],
                          widget: relation,
                          collection: pages,
                        }
                  - label: Link
                    name: link
                    fields:
                      - {
                          name: slug,
                          label: Link,
                          value_field: '{{slug}}',
                          search_fields: ['{{slug}}'],
                          widget: relation,
                          collection: links,
                        }
                  - label: Header
                    name: header
                    fields:
                      - {
                          name: slug,
                          label: Header,
                          value_field: '{{slug}}',
                          search_fields: ['{{slug}}'],
                          widget: relation,
                          collection: headers,
                        }
  - name: 'devcon'
    label: 'Devcon'
    label_singular: 'Devcon'
    folder: 'src/content/devcon'
    slug: '{{slug}}'
    create: true
    fields:
      - { name: 'number', label: 'Number', widget: 'number' }
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'description', label: 'Description', widget: 'text' }
      - { name: 'location', label: 'Location', widget: 'string' }
      - { name: 'startDate', label: 'Start Date', widget: 'date', format: 'YYYY-MM-DD' }
      - { name: 'endDate', label: 'End Date', widget: 'date', format: 'YYYY-MM-DD' }
      - { name: 'image', label: 'Image', widget: 'string' }

  - name: 'playlists'
    label: 'Playlists'
    label_singular: 'Playlist'
    folder: 'src/content/archive/playlists'
    slug: '{{slug}}'
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'description', label: 'Description', widget: 'text' }
      - { name: 'image', label: 'Image', widget: 'string' }
      - { name: 'categories', label: 'Categories', widget: 'list' }
      - { name: 'curators', label: 'Curators', widget: 'list' }
      - name: videos
        label: Videos
        widget: list
        collapsed: false
        field:
          {
            name: video,
            label: Video,
            value_field: '{{slug}}',
            search_fields: ['title'],
            display_fields: ['title'],
            widget: relation,
            collection: videos,
          }

  - name: 'videos'
    label: 'Videos'
    label_singular: 'Video'
    folder: 'src/content/archive/videos'
    slug: '{{slug}}'
    create: true
    nested:
      depth: 3
      summary: '{{title}}'
    fields:
      - { name: 'isFolder', label: 'Is folder', widget: 'hidden' }
      - { name: 'edition', label: 'Edition', widget: 'number' }
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'description', label: 'Description', widget: 'text' }
      - { name: 'youtubeUrl', label: 'Youtube URL', widget: 'string' }
      - { name: 'image', label: 'Image', widget: 'string', required: false }
      - { name: 'ipfsHash', label: 'IPFS hash', widget: 'string' }
      - { name: 'ethernaIndex', label: 'Etherna Index', widget: 'string' }
      - { name: 'ethernaPermalink', label: 'Etherna Permalink', widget: 'string' }
      - { name: 'duration', label: 'Duration', widget: 'number' }
      - { name: 'expertise', label: 'Expertise level', widget: 'string' }
      - { name: 'type', label: 'Type', widget: 'string' }
      - { name: 'track', label: 'Track', widget: 'string' }
      - { name: 'tags', label: 'Tags', widget: 'list' }
      - { name: 'speakers', label: 'Speakers', widget: 'list' }
    meta:
      {
        path:
          {
            widget: string,
            label: 'folder',
            index_file: 'index',
            hint: 'Should start with the Devcon edition (e.g. 4/talk-name) as specified in the next field',
          },
      }

  - name: 'profiles'
    label: 'Profiles'
    label_singular: 'Profile'
    folder: 'src/content/profiles'
    slug: '{{slug}}'
    create: true
    i18n: true
    fields:
      - { name: 'name', label: 'Title', widget: 'string', i18n: 'duplicate' }
      - { name: 'role', label: 'Role', widget: 'string', i18n: 'duplicate' }
      - { name: 'description', label: 'Description', widget: 'text', i18n: true }
      - { name: 'organization', label: 'Organization', widget: 'string', i18n: 'duplicate', required: false }
      - { name: 'country', label: 'Country', widget: 'string', i18n: 'duplicate', required: false }
      - { name: 'imageUrl', label: 'Image URL', widget: 'string', i18n: true }
