name: Import Twitter news

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          token: ${{secrets.GH_ACCESS_TOKEN}}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Import Twitter news
        run: yarn scripts:twitter-import
        env:
          TWITTER_API_KEY_NEWS: ${{ secrets.TWITTER_API_KEY_NEWS }}

      - name: Commit updates
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'CI Twitter import'
